build: migration and max withdraw updates
jmonteer/yearnv3-strat-compoundv3-lender pull request #6
Opened 2022-12-16 03:10 UTC by Schlagonia

2022-12-19 19:31 UTC, jmonteer requested changes

2022-12-19 19:31 UTC, jmonteer commented on contracts/BaseStrategy.sol
> +        require(amount <= _maxWithdraw(vault), "withdraw more than max");
use msg.sender instead of vault

2022-12-19 19:31 UTC, jmonteer commented on contracts/BaseStrategy.sol
> +        IERC20(asset).transfer(vault, amountWithdrawn);
use msg.sender instead of vault

2022-12-19 23:00 UTC, Schlagonia commented on contracts/BaseStrategy.sol
> +        require(amount <= _maxWithdraw(vault), "withdraw more than max");
https://github.com/jmonteer/yearnv3-strat-compoundv3-lender/pull/6/commits/c4637d7efa34f5f6c1b5b170cb39ac98001ec514

2022-12-19 23:00 UTC, Schlagonia commented on contracts/BaseStrategy.sol
> +        IERC20(asset).transfer(vault, amountWithdrawn);
https://github.com/jmonteer/yearnv3-strat-compoundv3-lender/pull/6/commits/c4637d7efa34f5f6c1b5b170cb39ac98001ec514

2022-12-20 08:44 UTC, jmonteer approved these changes

2022-12-20 08:44 UTC, merged